### ISSUE TITLE
After loggin page error

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/ayon-frontend#182]
This is happening to me after I have logged into the Ayon first time. 

![image](https://github.com/ynput/ayon-frontend/assets/40640033/08d4efaa-a3b5-402f-a56a-06940ea31acf)

If I hint couple times `Reload` button, it is finally loading the page.

**Comment by Innders** [comment]
Unfortunately there's not much we can do about this other than saying you need to reload the page.

When the server is updated the javascript file is re-built with a different name and so when the page tries to import the old file it can't find it.

One solution might be to catch this error and automatically reload the page for the user.
