### ISSUE TITLE
Cannot create new entries on project editor

### ISSUE THREAD

**Issue by maxpareschi** [ynput/ayon-frontend#215]
Ayon version: 0.4.7+2310060958

This is happening after .\manage.ps1 update and .\manageps1.build on an older version.
If I try to create:
- a new folder
- a new folder sequence
- a task
in the project editor I get the following error:

```
Something went wrong :(
TypeError: m.current.querySelector is not a function
```

**Comment by martastain** [comment]
Fixed in `0.4.7+2310061931`
