### ISSUE TITLE
Move Install Addons Button

### ISSUE THREAD

**Issue by beatreichenbach** [ynput/ayon-frontend#270]
Small nice to have request:

The "Install addons" button should be moved from the "Bundles" tab to the "Addons" tab.
It would probably also make sense to rename it "Install Addons" (capitalize Addons to match the rest.)

I assume this is currently done because it's convenient to bundle with other upload windows: https://github.com/ynput/ayon-frontend/blob/3e393ce4ad7d5c8e911d34e6ab28fc8641782717/src/pages/SettingsPage/Bundles/Bundles.jsx#L300

**Comment by tokejepsen** [comment]
The reason for having the `Install addons` button on the `Bundles` tab, is because a lot of development on the client side requires to modify the bundles.

Having it in both might be an option though.

**Comment by beatreichenbach** [comment]
That makes sense. I'll think about this a bit more, thank you!

**Comment by mkolar** [comment]
I agree that it would make sense to add it here as well, while keeping it on bundles too 

<img width="1087" alt="image" src="https://github.com/ynput/ayon-frontend/assets/3333008/3af8fedd-ab02-4a8a-9eaa-91fa9ec9a87d">

**Comment by Innders** [comment]
@LudoHolbik could we please put the addon install button and Dialog on the addons page like this:

Use the same button from bundles with same shortcut and tooltip.

![Image](https://github.com/ynput/ayon-frontend/assets/49156310/58c42790-b3d5-436f-8747-d1d73d159532)

**Comment by BigRoy** [comment]
I wonder if the argument for the Addon marketplace where the "Install" button needs to be renamed to "Download" also goes here. This **Install Addons** here is just uploading the addon - not necessarily installing it for production or alike?

I don't mind either, just wondering whether this may also be confusing wording to some.

**Comment by Innders** [comment]
I agree it would make sense to change to "upload addon".

**Comment by LudoHolbik** [comment]
Agree.
