### ISSUE TITLE
Crashing the event Viewer

### ISSUE THREAD

**Issue by stephenscollay** [ynput/ayon-frontend#303]
When syncing from Shotgrid to Ayon I have noticed that it is possible to max out the memory of the Event Viewer Page which requires a reload to fix.

![Capture](https://github.com/ynput/ayon-frontend/assets/50131715/64b08ce7-9518-4b63-ad41-0749647eb135)

**Comment by Innders** [comment]
Interesting, are you syncing a large amount of data?

**Comment by stephenscollay** [comment]
I should have put this above sorry but this is using the Shotgrid > Ayon sync button after having removed the shots in Ayon. I would not say a large amount, 4 shots each with 4 tasks. I'll be honest, I am not sure what the limitation is but it has occurred twice so I thought I may as well note it.
