### ISSUE TITLE
Dashboard > Tasks: Right click task "Open in Browser" fails

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-frontend#317]
When clicking on e.g. this context menu entry:

![image](https://github.com/ynput/ayon-frontend/assets/2439881/459c17d6-0bca-4725-856f-1cb2e5f555d4)

I get an error instead of it switching to the browser for that task.

![image](https://github.com/ynput/ayon-frontend/assets/2439881/f15c778d-de78-4b07-a257-e24ed348e591)

![image](https://github.com/ynput/ayon-frontend/assets/2439881/02a565b2-c453-4d56-8386-ceb67c4b2123)

---

Server: `1.0.8+202403281707`

**Comment by Innders** [comment]
#308 fixed this
