### ISSUE TITLE
Show shortcuts in context menus

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#321]
I'm a big believer of showing shortcuts repeatedly in context to the action, otherwise no one ever learns them.

But sometimes you just don't have a place to show the shortcut. For example: `ctrl+click` whilst collapsing a folder will collapse all child folders as well.

How can we inform this user of this shortcut?

Currently there is a forum post with all major shortcuts but that's not ideal...

https://community.ynput.io/t/ayon-web-app-keyboard-shortcuts/547

**Comment by mkolar** [comment]
I think, inside of the product the contextual way is good. This could be shown next to a context item in the right click menu, that should be there anyways. If you can't do something with a UI, no shortcut will make it obvious. 

This is the right way I think, as we do it in menus
<img width="422" alt="image" src="https://github.com/ynput/ayon-frontend/assets/3333008/e704ae44-610b-4052-8bb3-b4908d30e72c">
