### ISSUE TITLE
Browser: Show 'author' as nice user with icon

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-frontend#322]
### Issue

Currently the author on publishes in the "Browser" looks like:

![image](https://github.com/ynput/ayon-frontend/assets/2439881/f85a2605-2a51-4ab1-878a-1fcda4d32bb9)
(See `tom` top left hand side and bottom right hand side)

Even though the same user in the "Assignees" list in editor looks like:

![tom_hanks](https://github.com/ynput/ayon-frontend/assets/2439881/5fde5c9c-5f02-45b6-968e-05f9e1e456ae)

Is there any way to get the browser author to be nicely linked to the user's account and be visualized as such?

---

Bonus points for tooltips as described in #319 on these as well.

---

Server: `1.0.8+202403281707`

**Comment by Innders** [comment]
I'm assuming that the author field is linked to users as only users can publish new versions... @martastain ?

I like the idea of bringing it in line with how assignees look.

- [ ] Use the users `fullName` if it is available.
- [ ] Add the user avatar to left of the name.
- [ ] If the user does not exist (deleted) then the avatar should default to the first letter of `author`. `tom` -> `T`

**Comment by Innders** [comment]
> Bonus points for tooltips

What more information would be useful to see here? We are already seeing full name and avatar.

Possible useful fields.

- access level (admin, manager, user)
- member of teams (compositing)
- leader of a team (Director)
- Selected custom user attribute (no idea technically how that would work)

**Comment by martastain** [comment]
In most cases yes, but there's a catch - author may be also an identifier of an automation process, so it does not have FK to users.name. so the component displaying that field must be able to handle authors with no record in the DB.

**Comment by Innders** [comment]
> automation process

Is there anyway to tell between an automation process and a deleted user?

`An artist works on a production for two weeks and publishes lots of stuff but then leaves` <- extremely common.

**Comment by martastain** [comment]
I assume in that case the user should be marked as inactive and not deleted to keep other possible references intact.

**Comment by mkolar** [comment]
> I assume in that case the user should be marked as inactive and not deleted to keep other possible references intact.

That also points to the fact, that we should probably make it uber obvious that it's not a good idea to be deleting users once they've done something. But the question still stands. what to do when the user is actually deleted.

**Comment by martastain** [comment]
In this case, it should render author field without trying to show full name and icon. version.author does not have a strict reference to users table, because it was stated that author may be a "virtual" entity such as "farm" or something, not a particular Ayon user.

**Comment by Innders** [comment]
We are planning on completely replacing this details panel with the one used on artists dashboard. #388
