### ISSUE TITLE
Anatomy Settings FPS field typing 24 makes 2.04 instead of 24.0

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-frontend#328]
### Issue

In Anatomy settings when selecting the full Attributes > FPS field value to "replace" it with a new value, e.g. typing 24 I get this, `2.04` 
because it doesn't seem to want to "clear" the field and thus when typing `2` completes it to `2.0` and then typing `4` makes it `2.04` where I would like it to be `24.0

![image](https://github.com/ynput/ayon-frontend/assets/2439881/efdf7007-43d4-4b91-8835-00a1920efdb2)

---

Sidenote: 

When 0.0 in the field and then hovering with a cursor I get this:

![image](https://github.com/ynput/ayon-frontend/assets/2439881/63c6121f-fd8d-4c4c-a8f0-e22f89640719)

However, sometimes I also get stuff like this when just starting to type values:

![image](https://github.com/ynput/ayon-frontend/assets/2439881/39a4e967-5fec-4946-a468-4741f0eca144)

Not sure if really important since I had to really _try_ to break it to get those popups.

Anyway, pretty sure negative values should never be valid.

**Comment by martastain** [comment]
Is this a problem of the settings or InputNumber component? IIRC it was problematic to enter certain numerical values in the editor as well, am i right?

**Comment by BigRoy** [comment]
I wonder how the [listed change here](https://github.com/ynput/ayon-frontend/commit/882775423c3e6c94097154cafbdfb3aebd0b4079) fixes this issue - haha.
![image](https://github.com/ynput/ayon-frontend/assets/2439881/82eaf765-1a88-4921-be97-6ed27bae674e)

**Comment by Innders** [comment]
You've caught me, I committed to develop directly by accident and forgot mention the fix.

Then I used this "fake" commit to close the issue. Not best practice I know. 😨 Maybe there was a better way to fix it... I'm not git expert.

https://github.com/ynput/ayon-frontend/commit/29836b762ccde998d6041bf54ffbff9baccde38a

**Comment by martastain** [comment]
That sounds like something i would do :D

You are becoming an anarchist!
