### ISSUE TITLE
Editing field TAB key doesn't go to next field, but to "clear field" button when hovering with mouse

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-frontend#336]
**Describe the bug**

When editing folder attributes in the Editor, e.g. like this:

![image](https://github.com/ynput/ayon-frontend/assets/2439881/68d91a76-9665-4cc5-9bc3-19422388c0dd)

Then when the mouse is actively over the field to the right you get a "Clear field" button - which is all fine.
But unfortunately when you press `TAB` on the keyboard to e.g. start editing the next field that "Clear field" button takes focus first - which feels quite counter intuitive.

**To Reproduce**
1. Click on e.g. "Width" field to edit it (Keep your cursor over the field!)
2. Type a new value
3. To the right there should be a Clear field button
4. Press TAB to edit the next field, e.g. Height.

Focus is now on the Clear field button instead of the next attribute.

**Expected behavior**

TAB would go to the next attribute instead. The Clear Field button should not take focus.

**Screenshots**

![image](https://github.com/ynput/ayon-frontend/assets/2439881/68d91a76-9665-4cc5-9bc3-19422388c0dd)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 124.0.2 (64-bit)

**Additional context**

n/a

**Comment by Innders** [comment]
Should be a simple `tabIndex={-1}` on the clear button. Thanks @BigRoy

**Comment by LudoHolbik** [comment]
Thanks for noticing and yes, making clearfield unfocusable by tabindex is good suggestion.

I made a PR here https://github.com/ynput/ayon-frontend/pull/337
