### ISSUE TITLE
Filter only specific activity types

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#340]
### Stories

1. A sup just wants to see a list of versions.

![Image](https://github.com/ynput/ayon-frontend/assets/49156310/2a44780d-9561-4a73-860f-c1f74c1e6ef3)

**Comment by Innders** [comment]
Activity would have been for meta activities like "status.changed" and "assignee.added" but I think it can be replaced with "subtasks"

**Comment by martastain** [comment]
Also: https://github.com/ynput/ayon-backend/pull/148
