### ISSUE TITLE
Access level switch disappears after setting to service

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#355]
**Describe the bug**
Once a user is set to service there's no way to set them back to any other level.

**To Reproduce**
1. Go to /settings/users
2. Click on a user that has an access level NOT as a service
3. Set Access level to service
4. No way to get them back to original level

**Expected behavior**
The switch for access level would remain. 
![image](https://github.com/ynput/ayon-frontend/assets/49156310/83fe7ec1-c56a-4b38-8ac7-ea229bb5f486)

**Screenshots**
![image](https://github.com/ynput/ayon-frontend/assets/49156310/797a33c7-1031-41ad-b382-07da37b81cd6)

**Additional context**
 - `ServiceDetails.jsx`
 - `UserAccessForm.jsx` line 115

**Comment by martastain** [comment]
I would prefer not to be able to turn a regular existing user into a service account. 

If a user is created as "human" they should remain human and vice versa, services don't use additional metadata such as full name, they are not taggable in the activity feed, and changing switching between normal and service type could have weird consequences.

Selecting "service" should only be allowed when you create the user.

**Comment by Innders** [comment]
Service User can have:

- New service user Button
- username
- active/inactive
- create api key (APIKeyManager)

- Remove "service" access level switcher.
