### ISSUE TITLE
Typescript migration

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#360]
Is it worth starting to move over to typescript?

### Questions to be answered

- [ ] What are the advantages from a business perspective?
- [ ] What are the disadvantages and risks?
- [ ] Is it worth the dev time and money at this stage?
- [ ] Can we adopt it incrementally?
- [ ] Can types be automatically generated from the REST and Graphql api?

### Tests to be done

- [ ] Convert vite to typescript
- [ ] Generate types from API
- [ ] How long does it take to convert all these files?
     - [ ] ProfilePage.jsx
     - [ ] AccountPage.jsx
     - [ ] /services/user/getUsers.jsx

**Comment by Innders** [comment]
I think we can migrate incrementally. It would be good if some tests were done first though

**Comment by dee-ynput** [comment]
Ok, this is ready to be planned then ✨
