### ISSUE TITLE
添加Nuke 12.2 版本后项目的applications 找不到对应的Nuke 12.2 选项

### ISSUE THREAD

**Issue by liuyang199706** [ynput/ayon-frontend#375]
添加Nuke 12.2 版本后项目的applications 找不到对应的Nuke 12.2 选项

**Comment by Innders** [comment]
This is not directly related to the frontend of the AYON. Please join the discord and ask a question or post on the forum.

Please also provide more information about your problem so we solve it faster. Thanks.

Discord: https://discord.com/invite/ynput
Forum: https://community.ynput.io/
