### ISSUE TITLE
Bundles tootip issue

### ISSUE THREAD

**Issue by LudoHolbik** [ynput/ayon-frontend#379]
### Bug description
Minor tootip icon and text update. Icon currently looks like update of version is possible by clicking on icon. That is not the case,  it shows that user has installed addon that is a higher version than you he is using in the bundle.

### Solution
We want to replace it with more generic warning icon and update text accordingly. Conversation about issue [here] https://discord.com/channels/517362899170230292/1001811244535259207/1234784816784871497).

### URL
.../settings/bundles

### Screen - original state
<img width="1276" alt="image" src="https://github.com/ynput/ayon-frontend/assets/16327908/cda724b0-14eb-458c-96e5-485971449192">

**Comment by LudoHolbik** [comment]
1. Error icon:
<img width="580" alt="image" src="https://github.com/ynput/ayon-frontend/assets/16327908/7ac0f672-c497-4361-9432-aecf0d504a52">

2. Priority High icon:
<img width="574" alt="image" src="https://github.com/ynput/ayon-frontend/assets/16327908/cd61b356-e05e-40bb-a627-e7ac519894d0">

3. Info icon: 
<img width="575" alt="image" src="https://github.com/ynput/ayon-frontend/assets/16327908/5634d006-d782-4976-a87c-216fef8f7826">

**Comment by martastain** [comment]
Errors and warnings will be used for https://github.com/ynput/ayon-backend/issues/123 
And they should pop more (red/yellow) - this is just a preparation for the next step.

**Comment by Innders** [comment]
Great, let's go with 3 `info` icon.
