### ISSUE TITLE
Tasks: Select all assignees

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#389]
### Stories

1. A supervisor wants to view the tasks of all users.

### Problems

- Currently they need to select every single user 1 by 1.
- Should this even be allowed in the "tasks" view as a supervisor page would be better suited.

### Attachments

<img width="438" alt="image" src="https://github.com/ynput/ayon-frontend/assets/49156310/e63654db-bcb1-43f9-8db3-3a7008ed06f8">

**Comment by dee-ynput** [comment]
If the view can handle it (speed wise), I would not add another view for that. Team leaders will want to have this feature in the same context as their own tasks.

(We probably will need a Producers view for tasks, but with different objectives and UX)

Selecting team(s) instead of selecting users would be nice too.

**Comment by martastain** [comment]
1) Would it just remove the assignees filter, so it would show unassigned tasks as well? Maybe it should 

2) I'd limit that only to managers (and eventually the new production level role we dicussed)

**Comment by dee-ynput** [comment]
> 1. Would it just remove the assignees filter, so it would show unassigned tasks as well? Maybe it should

Seeing unassigned tasks is indeed very usefull!
What about a "Unassigned" entry in the drop down? So we can select Alice, Bob and Unassigned.
Disabling the filter could just show everything, as @martastain said.

If we have this, we can later add support for teams selection

> 2. I'd limit that only to managers (and eventually the new production level role we dicussed)
Not sure about that. Seeing Tasks assigned to coworkers sounds legit.
Or maybe as default behavior, and restrictable with ACL?

**Comment by Innders** [comment]
> 2\. I'd limit that only to managers (and eventually the new production level role we dicussed)

This already happens, only admins and managers see that filter. Normal users can only see their own tasks.

**Comment by dee-ynput** [comment]
I keep forgeting I'm logges as admin everywhere... 😓
Then we'll see later if users request access 😌
