### ISSUE TITLE
Dialog: Visual fixes

### ISSUE THREAD

**Issue by LudoHolbik** [ynput/ayon-frontend#396]
## Story

Dialog component has still some visual issues. I will make summary of them here and fixed them together.

### To reproduce

1. Font is blurry in at least two places. Most likely CSS issue, by switching overflow: auto is triggering this issue
- Copy Settings
.../manageProjects/projectSettings?project=demo_Big_Feature#
- New Project
.../manageProjects/anatomy

2. Dialog size issue
- New project

### Expected behavior

Fix visual issues for Dialog.

## Environment

- **Server version**: 
- **Server host OS**: 
- **Browser**: 
- **Client version**:

**Comment by Innders** [comment]
This issue is due to `translate: -50%, -50%`. It will need to be fixed in ayon-react-components.

https://issues.chromium.org/issues/41477985
