### ISSUE TITLE
Editor: Creating task visually inherits description from parent where it should not

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-frontend#397]
## Story

In the project editor, when creating a new task under a folder that has a description the frontend will visually display it inherits the description, whereas _description_ is not an inheritable attribute and thus it should not.

@martastain stated:
> description is not an inheritable attribute so displaying it in the optimistic update is a frontend bug.

![image](https://github.com/ynput/ayon-frontend/assets/2439881/48fe4bb4-757e-41a6-a8f0-3c99039f5a19)

### To reproduce

1. Create a folder with description, save it.
2. Create a task in the folder, note how it shows cursive "description" on the task.
3. It remains on save.

It's gone after a refresh (it's just a visual bug on create it seems?)

### Expected behavior

It should not show any inherited description.

## Environment

- **Server version**:  1.1.0+202405081147
- **Server host OS**:  Windows
- **Browser**:  Firefox
- **Client version**:  n/a?

### Additional context

Reported on [discord](https://discord.com/channels/517362899170230292/890894521817260052/1238424061969694770).

**Comment by BigRoy** [comment]
Question by @Innders on [discord](https://discord.com/channels/517362899170230292/890894521817260052/1238487047254179923):

> Are there any other attrib that are not inheritable and how do I know which ones are and aren't?

@martastain - might be good to track the answer here too.

**Comment by martastain** [comment]
There's a boolean flag on attribute. It is configurable:
![image](https://github.com/ynput/ayon-frontend/assets/5007200/90bf6815-1224-4baf-86de-c5f7c669dede)
