### ISSUE TITLE
Market: Download other versions

### ISSUE THREAD

**Issue by iLLiCiTiT** [ynput/ayon-frontend#410]
## Story
I don't want to use latest version and want to download earlier version because I have other addon that is not yet compatible with a latest addon.

### Problems
Only latest addon version can be downloaded from addon market.

### Proposal
Be able to download any version available on ynput cloud.

**Comment by Innders** [comment]
Added small dropdown icon that will list all available downloads and show versions already downloaded.

You will be able to download the same addon again.

<img width="1920" alt="Marketplace_Selected_v004" src="https://github.com/ynput/ayon-frontend/assets/49156310/4ee386a4-2056-4fe5-90b8-8764c3a468e3">
