### ISSUE TITLE
Bootstrap: Show addon version on pick addons page

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#430]
## Story

A user wants to know if a particular addon version is included in a release.

### Proposal

- On `AddonSelectStep` show each addon with it's version.
- Grid columns to 2

### Attachments

![image](https://github.com/ynput/ayon-frontend/assets/49156310/946f328f-3ba1-4a7d-b4bd-28e279807e4f)

**Comment by BigRoy** [comment]
I wonder if on the Addon Marketplace whether it's worth it for an addon to also show "Included in Bootstrap X".
