### ISSUE TITLE
Testing: Setup Playwright end-to-end testing and write first tests 

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#432]
## Story

We make a small change in one area and accidently prevent new users from signing up. (This actually happened)

### Problems

When something is merged we cannot guarantee that everything is still working just by clicking around the app, it is very easy to miss unintended side effects.

### Proposal

We use [Playwright](https://playwright.dev/) as a testing library.

We start with critical tests only and add more overtime.

## TODO

- [ ] Install playwright
- [ ] Create first few tests
- [ ] Create a new ongoing issue documenting new tests that need to be written

**Comment by gibsonliketheguitar** [comment]
@Innders Can I help with this?

**Comment by Innders** [comment]
> Can I help with this?

Sure, feel free to contribute to this PR: https://github.com/ynput/ayon-frontend/pull/444

I had it all working and then at some point it stopped...

**Comment by dee-ynput** [comment]
@mkolar do we want to invest more time here?
Tests are important for the frontend team, but the business value is... mitigated 😝

**Comment by mkolar** [comment]
I'd say it's definitely worth it. without FE testing, we'll keep running into the same things again and again.
