### ISSUE TITLE
Browser: replace prime react dropdown

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#476]
![image](https://github.com/ynput/ayon-frontend/assets/49156310/f3961d0b-eedd-413f-84f2-d41945542511)

**Comment by BigRoy** [comment]
Should we try and get the statuses next to it in the dropdown, similar to here: https://github.com/ynput/ayon-core/pull/564#issue-2323592177

Or is that technically what this issue is about?

**Comment by Innders** [comment]
> Should we try and get the statuses next to it in the dropdown

Not what this issue is about but technically can be done.

@mkolar what do you think about having the status icon on right of each version dropdown item?
