### ISSUE TITLE
Dashboard: Tasks should use latest version thumbnail if no task thumbnailId

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#478]
Currently only task thumbnails or nothing is shown even when a product has a thumbnail.

Which products thumbnail is shown as a task can be linked to multiple products?

**Comment by BigRoy** [comment]
For context here's a screenshot. I have a product for this task with a thumbnail - but the task itself does not "borrow" it as thumbnail if it has no explicit thumbnail set.

![image](https://github.com/ynput/ayon-frontend/assets/2439881/273cb550-b988-4080-b22d-3882c7c2fbe7)
