### ISSUE TITLE
Attributes: Make greater than fields more human friendly

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#479]
![image](https://github.com/ynput/ayon-frontend/assets/49156310/aa436561-0a9c-4593-a2e1-ffb366278106)

Two fields:

Less than
Greater than

And there is a button toggle for "or equals"

**Comment by BigRoy** [comment]
Sorry, could you explain what these fields mean on an integer field?

Wouldn't is just be: "Minimum" and "Maximum"? And maybe a "soft minimum" and "soft maximum" which usually refers to the range a slider would default to, like a default slider start and end.

**Comment by martastain** [comment]
As this PR aims to make fields "more human friendly" i am not the target audience, but i had to google "soft minimum" (not many relevant results actually). I'd find it really confusing. I believe "less or equal" and "great or equal" are both self-explanatory and it is how it is attached on elementary schools (at least here).

**Comment by BigRoy** [comment]
Just for context - some references from DCCs.

Maya:
![image](https://github.com/ynput/ayon-frontend/assets/2439881/5eb0fdb1-ef21-4019-bce6-5fd00e73d5b0)

Blender:
![data-system_custom-properties_edit](https://github.com/ynput/ayon-frontend/assets/2439881/bf53dce7-2413-49a7-9c7a-33ef2a0e8965)

Houdini:
![image](https://github.com/ynput/ayon-frontend/assets/2439881/19782254-286e-4745-bd4e-d40450f2f1d7)

The _lock_ icon here is a UI hint: 
![image](https://github.com/ynput/ayon-frontend/assets/2439881/b825f48f-2622-4498-969f-730b926033f7)

**Comment by BigRoy** [comment]
> I believe "less or equal" and "great or equal" are both self-explanatory and it is how it is attached on elementary schools (at least here).

Yup - sorry, I initially thought it was the difference between a UI-slider hint min/max and an actual value min/max but it seems to just be the last and mean that the value may _include_ the min/max value itself or not.

**Comment by Innders** [comment]
I think we are being stupid here... if it's an **integer** it makes no sense to have **_more than_** or **_more than or equals_** and more than.

Min and max will enough.

Floats might need this because you can have 9.999999999999999.

**Comment by BigRoy** [comment]
> Floats might need this because you can have 9.999999999999999.

This guys floats.
