### ISSUE TITLE
Tag versions: Easier access to latest versions when tagging version entities

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-frontend#480]
## Story

As an artist or producer I want to comment about a particular published product in e.g. a task, so I use `@@` to get the autocomplete list for the products. Usually I want to refer to the more recent published products.

### Problems

It seems that the versions listed are unsorted in the pop-up:

![image](https://github.com/ynput/ayon-frontend/assets/2439881/fc895395-9d01-4788-adbf-202875ac763f)
`1.1.3+202405301422`

And worse, with multiple products under a folder or task it may be unclear to what product the version is referring.
It is capable of adding a more descriptive name.

![image](https://github.com/ynput/ayon-frontend/assets/2439881/3599eeb7-0256-41ce-8291-e55131acffe3)
![image](https://github.com/ynput/ayon-frontend/assets/2439881/ed041eef-3ee9-4dbe-b5f9-b64dc1d98010)

However, it only does so if the "currently filtered list" includes multiple products - but if the five entries that it happens to show now or have filtered (e.g. like above by default) it's unclear which of the products those are.

---

#### Nicer preview of the tag in the comment itself, possible?

Side note: When having a tag in your active comment field then clicking the tag itself pops up this:

![image](https://github.com/ynput/ayon-frontend/assets/2439881/d011e26b-df6a-458e-8bb9-8aa5279f6be4)

But it would be nice to have it display similar to this:
![image](https://github.com/ynput/ayon-frontend/assets/2439881/d3c955d6-ae51-440c-a7c5-9b0af9408af6)

(But yes, then where does the "Remove" button go)?

### Proposal

List the versions sorted with most recent versions at the top and always show the product name for clarity.

- [x] Always include the product name suffix
- [x] Sort the entries in the auto complete with most recent publishes first
- [ ] #486

### Attachments

Server: `1.1.3+202405301422`

**Comment by Innders** [comment]
How does this look? 

![image](https://github.com/ynput/ayon-frontend/assets/49156310/6584e0a0-6765-4804-99d1-d64ffca09671)


(It was meant to be sorted by `createdAt` already but it was broken)

**Comment by Innders** [comment]
A small side effect is that task mentioning now has parent folder prefixed which will be required for #475 

![image](https://github.com/ynput/ayon-frontend/assets/49156310/4fe9e88d-2ad7-4e7d-907e-65cff43bf67d)

**Comment by BigRoy** [comment]
> How does this look?
> 
> ![image](https://private-user-images.githubusercontent.com/49156310/335561508-6584e0a0-6765-4804-99d1-d64ffca09671.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNTY3ODIsIm5iZiI6MTcxNzE1NjQ4MiwicGF0aCI6Ii80OTE1NjMxMC8zMzU1NjE1MDgtNjU4NGUwYTAtNjc2NS00ODA0LTk5ZDEtZDY0ZmZjYTA5NjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDExNTQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwMjBiYjlmYzY3MTEzYjlhNzZlZjg4OTVhOWYzMjhlMjlkZDBjZGNmZDQ5ZjY1ZmM5NmYyZTI1NDIyMGVkZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dOgVF-dnb89FhnWUvFhWun9bEllghZtzmG--1XLQwAo)
> 
> (It was meant to be sorted by `createdAt` already but it was broken)

Lovely!

I'm still doubting whether this should eventually be a two step process, like `@@` then pick the product, then the version but that'd be much slower in the many cases you don't need to scroll that far. So let's go with this, yes!

**Comment by Innders** [comment]
> I'm still doubting whether this should eventually be a two step process

When linking comes into play, the whole mentioning system might need to be rethought anyway.

It also occured to me that it's not obvious what you are actually seeing, so maybe a little header that changes could help.


https://github.com/ynput/ayon-frontend/assets/49156310/2f1d0bdf-4ece-4ba5-9cea-1cd76817b8d6

**Comment by Innders** [comment]
> Or otherwise use the product type icon?

I think thumbnail is totally overkill. Product icon might make sense... but you are pick a version and not a product so that might confuse things. Although the versions icon will always be the same, so is it pointless having it there?

**Comment by BigRoy** [comment]
I see what you're saying. I do still think having the product type icon here is more representable than the version - unless maybe hero version is something you'd need to be way more distinctive upon.

Another plus of using the product icon is that with the change proposed here the product name comes first, and the icon is well, next to it. :)

**Comment by mkolar** [comment]
I'd say the last @Innders proposal is starting to make sense. It's more a question of fast and intuitive filter than showing everything. For instance when typing `@@` It will need to be fully contextual:
- When I'm commenting on a version: Show other versions of the same product
- When I'm commenting on a task: show latest version of each product with the product name first, but when I type `ani` tweak the tooltip to only show those version whose product start with `ani`

So typing `@@` on v004 of a product `modelMain` would show:
```
modelMain - v003
modelMain - v002
modelMain - v001
```

Typing `@@` on a task `modelling` would show:
```
modelMain - v004
modelBroken - v004
modelProxy - v001
```
but when I continue with `@@Mai` I'd expect to narrow it down to 
```
modelMain - v004
modelMain - v003
modelMain - v002
modelMain - v001
```

IN general I think we'll be iterating here until it feels good rather than engineer a solution, but let's keep trying
