### ISSUE TITLE
Inbox: New message notifications

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#499]
## Story

I'm working on something different but I want to know when I have an important message in AYON

### Problems

There's no notification (other than inside AYON) that lets users know they have an important message.

### Proposal

1. The browser title updates to show new message.
2. The browser favicon updates with new message.
3. Chrome taskbar on windows has notification message?

Future: proper notification messages for different operating systems, togglable in account settings.

### Attachments

![image](https://github.com/ynput/ayon-frontend/assets/49156310/8258e04b-1047-40ff-aa4f-910bdfc0aca5)

**Comment by krishna8008** [comment]
I would like to request a (bell) sound as well when a notification occurs, if possible...
A small popup appears at the bottom left, which quickly appear and goes away in few seconds, this might give glimpse on what was notification!?
