### ISSUE TITLE
Details Panel:  Click on path to open slide out

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#508]
## Story

You are looking at a version/shot/task and want to see it's parent.

![image](https://github.com/ynput/ayon-frontend/assets/49156310/980bbf13-aeb4-4c61-8ac1-bb69790603cc)

### Proposal

Each part of the path becomes a clickable link that would open the slide out panel for that entity.
![image](https://github.com/ynput/ayon-frontend/assets/49156310/3c6f3c8d-e67b-4a01-8262-96904977f30c)

Can you open products?

**Comment by martastain** [comment]
Being able to copy the entity ID would be super useful. Possibly via context menu (if that's possible for each of the elements, it would be the greatest)
