### ISSUE TITLE
Editor: Setting tool override does not persist the inherited values

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-frontend#546]
## Story

When in the Project Editor and you want to enable or change the used tools on a folder or task that currently does not have any overrides it by default show "inherited" as value.

When opening the dropdown to change the tools as an override that dropdown does not include the "inherited" tools (from e.g. the project anatomy or parent folders) and thus as soon as you click one tool, then the override you're making is completely removing all inherited tools as well instead of just "adding the one you clicked"

In the below steps the inherited value is "arnold" yet just 'adding' "mgear" from the dropdown also removed "arnold" because it doesn't actually 'inherit' it in the dropdown by default.

![image](https://github.com/ynput/ayon-frontend/assets/2439881/55804b3b-483b-4e98-8a54-dc579093702b)

![image](https://github.com/ynput/ayon-frontend/assets/2439881/45cce267-b8ea-4292-8517-4abf55cf8dc1)
_this maybe also showns a line height issue in the dropdown menu if the window is small? screenshot is from `1.2.3+202406201258` with firefox with window resized small_

![image](https://github.com/ynput/ayon-frontend/assets/2439881/0937fcfa-3306-4aeb-9aca-1e2f9ff17a4b)

### To reproduce

1. Add tools to project anatomy 
2. Create a new folder
3. Save + refresh (just to make sure it's not an optimistic update issue)
4. Select folder, add a different tool to that folder to add it.
5. Now it also has lost its inherited values

### Expected behavior

I would expect by default the inherited values to be visible in the tools dropdown (and selected) and as soon as you change one selection e.g. disabling/enabling a tool then the result of that is the overridden value.

## Environment

- **Server version**: `1.2.1+202406181051` and `1.2.3+202406201258`
- **Server host OS**: Windows
- **Browser**: Firefox and Chrome
- **Client version**: ?

**Comment by martastain** [comment]
That seems to me like a reasonable request.

@Innders Maybe we could pre-populate the dropdown as soon as user opens it? But i that case, we should probably commit the value only if there is a change.

I'd like to also summon @iLLiCiTiT here - there are plans to change applications and tools behavior completely so maybe we'd be fixing something that will change soon.

Anyways - this could be useful for other inherited attributes as well

**Comment by iLLiCiTiT** [comment]
> I'd like to also summon @iLLiCiTiT here - there are plans to change applications and tools behavior completely so maybe we'd be fixing something that will change soon.

That is true, but list attributes will still exist.

**Comment by BigRoy** [comment]
> So let's say you open the dropdown, how should it behave? If the inherited values become preselected, what happens if you don't want those values now? Clicking away can only save those new values.

You'd deselect them, yes. There could maybe be a 'clear all' AND a 'back to inherited' (or whatever) button but admittedly the list showing what the values are now is what I'd expect, and if I want to change it I'd then change it from the current state.

**Comment by mkolar** [comment]
With the move of tools to settings. I'd say this is now obsolete

**Comment by BigRoy** [comment]
> With the move of tools to settings. I'd say this is now obsolete

Agreed
