### ISSUE TITLE
Entity Panel: Show entity IDs when dev mode on

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#550]
## Story

A developer wants to quickly see the ID of an entity.

### Solution

When in Dev mode show a copy button for the entity ID inside `DetailsPanelHeader.jsx`.

- Only shows when in dev mode
- Hover effect
- Text selectable
- Click to copy to clipboard (helper function somewhere)
- Overflow hidden (does not wrap)

![image](https://github.com/ynput/ayon-frontend/assets/49156310/015a1c87-3934-4802-846f-de1a32d33ef9)

**Comment by martastain** [comment]
quickly see and preferably copy :)

**Comment by Innders** [comment]
You can now right click on any part of the path to view and copy ID.

Fixed by #692 

![image](https://github.com/user-attachments/assets/b1e23847-0cbc-44bd-9c5b-eb675b2ae884)
