### ISSUE TITLE
Bundles: Re-check of compatibility on path change

### ISSUE THREAD

**Issue by iLLiCiTiT** [ynput/ayon-frontend#589]
## Story
In dev bundles it is possible to define custom path for client code. Each change of the path field is considered as addon change and combination of addons is re-validated for compatibility.
### To reproduce
1. Create dev bundle.
2. Enable custom path on a addon.
3. Start to fill path manually.
4. The label showing validation should start flickering as you type.

### Expected behavior
The path field does not affect in any shape or form the compatibility so the check can be skipped (the same for the checkbox that enables the path).

**Comment by Innders** [comment]
- [ ] Skip compatibility check for path changes.

`/settings/bundles`

Dev mode docs: https://ayon.ynput.io/docs/dev_dev_mode/#enabling-developer-mode

![image](https://github.com/ynput/ayon-frontend/assets/49156310/0feb43ad-cbc7-411b-8e0e-75da938251c4)
