### ISSUE TITLE
Addons sorting in addons tab

### ISSUE THREAD

**Issue by iLLiCiTiT** [ynput/ayon-frontend#599]
## Story
List of versions in Addon tab seems a bit random in default state. It is hard to compare them to currently used versions, and easily detect really old versions.

### Proposal
Sort addon versions using semver in Addons tab from newest to latest. Not sure what is current default order of versions but it seems to be random.

#### Current default state
![image](https://github.com/ynput/ayon-frontend/assets/43494761/e2c11738-fca0-41f4-a152-c9d0c7292ae6)

#### Expected default state
Note that the versions sorting does not have to be enabled...
![image](https://github.com/ynput/ayon-frontend/assets/43494761/09b6bb3c-598b-403d-9acd-599d654dc291)

**Comment by iLLiCiTiT** [comment]
> However, it seems that it's sorting ftrack.1.1.6-dev.1 higher than ftrack.1.1.6 and as such it seems alphabetical sorting currently instead of semver sorting?

Modified screenshot.

**Comment by Innders** [comment]
So `ftrack.1.1.6` should be higher than `ftrack.1.1.6-dev.1`?

**Comment by iLLiCiTiT** [comment]
> So ftrack.1.1.6 should be higher than ftrack.1.1.6-dev.1?

Yes, `1.1.6` is release version. Anything with dash or plus after that is lower than release version, e.g. `1.1.6-alpha.1`, `1.1.6-beta.2`, `1.1.6-rc.1`. That's how semver defines it.

**Comment by Innders** [comment]
@flynput looks like the sorting for the versions can be done here -> https://github.com/ynput/ayon-frontend/blob/763e8ba34d90a3870ccb9941a4bc3e402d05f85f/src/pages/SettingsPage/AddonsManager/helpers.js#L97.

You will want to use semver package already installed plus the additional sorting when the versions has extra suffixes (-dev.1).

https://www.npmjs.com/package/semver
