### ISSUE TITLE
Feed: GIF support

### ISSUE THREAD

**Issue by dee-ynput** [ynput/ayon-frontend#601]
## Story

As a user, I want to be able to share a GIF animation in activity feeds.

origin: [discord](https://discord.com/channels/517362899170230292/517380724618428416/1257357167212630106)

**Comment by Innders** [comment]
1. If the GIFS are useful then they can be attachments.
2. If the GIFS are "funny" gifs... this is not a social media app.

![NOPE](https://media1.tenor.com/m/hqze9KtFA0sAAAAC/blocked-kid.gif)

Closing for now.
