### ISSUE TITLE
Viewer: Use start frame 1 instead of 0 for media without timecode metadata

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-frontend#611]
## Story

In the vein of #610 but with no timecode present we should default to 1 instead of the (maybe programmatically correct) 0.

Video players like Syncsketch and DJV player seem to start at frame 1 instead of 0 as well.

### Problems

First frame (without timecode metadata) is 1 or 0?
- 0-49 (duration: 50)
- 1-50 (duration: 50)

For producers and artists the latter entry may be easier.

## TODO

- [ ] Start at frame 1 instead of 0 when no timecode metadata is exists.

**Comment by Innders** [comment]
Maybe it's worth tackling #610 at the same time?
