### ISSUE TITLE
Create new project: Tools sometimes do not initialize correctly from preset

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-frontend#634]
## Story

When creating a new project - it can happen that that "Tools" attribute remains empty even if the Anatomy Preset used does have Tools configured by default.

### To reproduce

It may be tricky to reproduce - but a client faced this on another platform (Linux?) and browser (I think "Opera"?) and I reproduced in Firefox Windows.

1. Configure an anatomy preset with a few "Tools" enabled by default.
2. Save the preset, configure it as the default
3. Go to "Home" > "Overview" `{ayon_url}/dashboard/overview`
4. Press CTRL+F5
5. Click Create Project
6. The Tools remain empty

![image](https://github.com/user-attachments/assets/3ce679be-f8fc-444b-b5f1-8f78c01576f6)

7. Closing the Add New Project, and reopening it again, suddenly shows it:

![image](https://github.com/user-attachments/assets/fdf4a55a-4409-4142-8247-e572b2ed1441)

8. CTRL+F5 and Click Add New Project
9. Tools remain empty again.

### Expected behavior

The anatomy preset should work as intended and have all the attributes work consistently. :)

## Environment

- **Server version**: 1.3.1+202407181622
- **Server host OS**: Windows
- **Browser**: Firefox
- **Client version**:

**Comment by martastain** [comment]
From your description it seems that cache invaildation in the frontend fails. I wasn't able to reproduce the issue, but I can see that Create New Project dialog indeed uses a cached version of the selected anatomy preset if it's available.

Note for tomorrow me: setting a preset as default should invalidate existing default

**Comment by martastain** [comment]
A second note for tomorrow me: it might be actually caused by the settings editor - I was able to reproduce it and the last response contained tools, that weren't displayed :-(

![image](https://github.com/user-attachments/assets/7daa4d72-9003-4272-9c8a-cb2623ab0370)

**Comment by martastain** [comment]
![image](https://github.com/user-attachments/assets/3c29e1c6-ac17-4eb4-beb7-2193645542ea)
![image](https://github.com/user-attachments/assets/b5bf5cc1-9b8e-40a8-96b4-efb94a430cce)

The issue is indeed in the settings editor. When i swap the order of applications and tools attributes, the later is affected again. Also, when i collapse the attributes tab and open it after the dialog is created, dropdown is always populated. There's most likely a  race condition when the form is populated with data.

**Comment by martastain** [comment]
I am no longer able to reproduce it after a slight change of form loading logic. Feel free to reopen this if the problem persists.

**Comment by BigRoy** [comment]
Confirmed - works.
