### ISSUE TITLE
Web Viewer: Snap playhead indicator to frame position

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-frontend#643]
## Story

It should be clear what frame I am on, also from the playhead indicator in timeline.

### To reproduce

1. Upload video of e.g. 5 or 10 frames
2. Click through timeline of reviewable.
3. The playhead indicator stays where you clicked - _except!_ for the last frame... there's a large area where it snaps back to the last frame.

E.g. this is further current frame playhead indicator would go when clicked
![image](https://github.com/user-attachments/assets/1b333994-7b7f-4cf1-9bb6-e146df964329)

But any of these are all frame 9
![image](https://github.com/user-attachments/assets/74ef18e8-d2f1-41ae-a6b5-0ee98f12a227)
![image](https://github.com/user-attachments/assets/469f8c38-abd4-47b4-b206-3af2bf37fc67)
![image](https://github.com/user-attachments/assets/f18639e8-b6e8-47ab-87b2-db54536d69f6)

### Expected behavior

Either ALWAYS snap to the frame - or allow the last frame to also go beyond as if that's still the frame to not have just that frame snap.

I'd vote always snap.

## Environment

- **Server version**: `1.3.1+202407191348`
- **Server host OS**: Windows
- **Browser**: Firefox and Chrome
- **Client version**:

**Comment by martastain** [comment]
Maybe, in the case frameCount < width, we should make the playhead indicator thicker to represent the entire frame on the timeline. Also we could highlight individual frames on the timeline (for example using alternating background color).
