### ISSUE TITLE
URI: Pass URI in URL to be resolved

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#669]
## Story

I want to share a full link to a specific entity with someone.

### Problems
- The URI currently doesn't work on all pages, like profile, users etc. It only works with entity browser and settings.
- The current technical implementation is quite messy and could do with a rethink.

### Proposal

- [ ] URI bar has a second button to copy full link with URI attached.
- [ ] `?uri=...` query param that is resolved.

![image](https://github.com/user-attachments/assets/7cb462a3-de54-4ac6-b01c-a89dea180c8c)

**Comment by BigRoy** [comment]
Ha! Can't vote for this enough - yes please!
