### ISSUE TITLE
Browser: addon could add Action to context menu

### ISSUE THREAD

**Issue by kalisp** [ynput/ayon-frontend#681]
## Story
As an addon developer I would like to expose some functionality based on context (from Browser). Eg. I would like to run some action on folder/task level.
<img width="298" alt="chrome_xz9Uj0h3rP" src="https://github.com/user-attachments/assets/2e413016-df8b-4b4d-a51d-b51dfe15ac9d">

### Problems
Jira addon has own frontend which allows leads/TDs to run some automatization (creation of tickets) based on selected context. (Eg. they select '/characters/Robot', they would like to click in context menu "Create tickets here", which would lead to addon's frontend where field would be prefilled based on selected context.)
Or it could be just endpoint where context would be injected

### Proposal
Addon should allow to create Action item which would be shown in Browser (maybe Editor) tab (in similar fashion as Loader could show Actions from addons)

**Comment by BigRoy** [comment]
For now this could be tackled by Web Actions already (it may not display on the context menu) but it would display on the entity sidebar.
