### ISSUE TITLE
Settngs: Decimal point values are hard to enter because 0 is not allowed

### ISSUE THREAD

**Issue by BigRoy** [ynput/ayon-frontend#683]
## Story

When trying to enter decimal point values like 0.01 the settings UI isn't very cooperative, because you can't start by typing `0` because that's not allowed. So you've got to start with e.g. `,` or `.` (depending on your browser locale?)

So then you type `.01` and save - and it saves... but then looking at the value again there's nothing there? It appears empty?

![image](https://github.com/user-attachments/assets/88a415a8-0967-4472-b1e2-e3661f990f47)

Then I want to correct it, and type .01 again, and then add the 0 before it. But then I can't save because the publisher UI doesn't detect it as a difference. So I save value as 2. And then try again to set 0,01... stll no changes detected?

![image](https://github.com/user-attachments/assets/1d4759bb-52de-4cc0-98bd-c1d66f0fbe70)

Then trying in chrome it makes slightly more sense, because then typing ,0 is also disallowed. So I need type `,1` and then put the zeros in front to make it `0,01` and then it's allowed.

What is UP?

### To reproduce

1. Find a float settings attribute that does not allow a value of 0 but does allow decimal points.
2. Try entering 0.01
3. Good luck! 😈 

My example test was done with `ayon+settings://blender/unit_scale_settings/base_file_unit_scale`

### Expected behavior

It should be easy to enter such a value and should maybe disallow 0 only when it detects it as the "final value"?

## Environment

- **Server version**: 1.3.1+202407231806
- **Server host OS**: Windows
- **Browser**: Firefox
- **Client version**: 

### Additional context

Reported [here](https://github.com/ynput/ayon-blender/pull/15#pullrequestreview-2205329398) by @LiborBatek 

I believe this came up before but I can't find it anymore. :)

**Comment by BigRoy** [comment]
Also, this may be worse and may not affect ONLY 0.xx values.

This example issue came from [this settings attribute](https://github.com/ynput/ayon-blender/blob/develop/server/settings/main.py#L22-L24) which does not have any explicit minimum or maximum set?

**Comment by Innders** [comment]
I really thought I had fixed this @martastain
