### ISSUE TITLE
Multiple selection on tasklist crashes the webapp

### ISSUE THREAD

**Issue by NeirdaP** [ynput/ayon-frontend#71]
Hi,

I installed Ayon via docker on a clean debian and setted up the demo projects.

When I try to select multiple tasks on the task list, the all webapp disappears (see gif below)

![crash_multiple_task_selection](https://user-images.githubusercontent.com/20859383/229382801-e5ce6273-f1f2-4955-8569-9561fd9e2c1d.gif)

I can see two `RangeError: Invalid time value` errors in the console when it happens.
I tried the same manipulations on _ayon.cloud_ and I have the same "crash".

Hope this feedback is useful :)

**Comment by Innders** [comment]
Thanks for flagging this, fixed now. Please feel free to create more issues if you find them! :)
