### ISSUE TITLE
Hierarchy: Unexpected expanding of folders

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#716]
### To reproduce

1. Expand some folders
2. Select a child folder
3. Hide (un-expand) top folder
4. Select a different folder
5. Previously hidden folder now unexpectedly opens

### Expected behavior

- Expanded folders stay the same (it doesn't randomly open).

### Additional context

https://github.com/user-attachments/assets/6521b831-5f4d-4f50-82a5-5e17fbb149c4

**Comment by robertokker** [comment]
Also expending all with CNRL click does work in the editor but not in the browser
