### ISSUE TITLE
Upload to AWS instances is very slow

### ISSUE THREAD

**Issue by 64qam** [ynput/ayon-frontend#747]
An upload to AWS Ayon instances over Ayon UI is very slow. Uploading all three launchers (approximately 930 MB) takes between 3 to 6 minutes, depending on the location. From Prague, the upload speed is 5 MBps, from Amsterdam 4 MBps, and from London 2.5 MBps. On the Hetzner instance, the upload corresponds to the internet bandwidth at the location. The same issue occurs when uploading comment attachments. However, when using the Ayon Python API or Bootstrap, everything works normally and the entire process takes around a minute (similar to the Hetzner instance).
Also investigating with Lara provider.

**Comment by martastain** [comment]
Solved by fixing ingress configuration
