### ISSUE TITLE
Remove 'Create first project' button from dashboard page for non-admin users when no projects are assigned to it

### ISSUE THREAD

**Issue by flynput** [ynput/ayon-frontend#753]
Users with no project creating credentials and no assigned projects are shown a 'Create first project' button when visiting the dashboard. This should be hidden, attempting to create a project will fail anyway.

![image](https://github.com/user-attachments/assets/f940102e-5523-49f0-a2a3-789ba6ca0edb)

**Comment by Innders** [comment]
Whilst we are at it, can we also sort out the styling of the button for when the user does see the button.

- [ ] Remove button for regular users.
- [ ] Button should be wider and higher. `padding: 8px 16px;`
- [ ] Move the button so it is below the "No Projects" text.
