### ISSUE TITLE
Settings: Display warning for clipboard paste errors due to browser permissions

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#762]
## Story

You try to copy and paste settings from one setting to another but the Paste Data dialog appears. This is most likely because there are browser permission errors. We should let the user know how to the fix the permissions.

### Proposal

Add a little note with a tooltip to the dialog header. If there is ever documentation of this, the tooltip could link to it.

![image](https://github.com/user-attachments/assets/17ec6a3e-6564-404b-93d5-b707a0e80440)

### Notes
https://stackoverflow.com/questions/64541534/check-whether-user-granted-clipboard-permisssion-or-not/64541730#64541730

**Comment by BigRoy** [comment]
Just as a sidenote - this is all related to "Pasting" but the issue or discussion internally came from a client reporting the issue that right clicking "Copy" didn't put anything in their clipboard.

So, a note may also need to be presented already on "Copy" too if detected.

---

Also, for context. This is what e.g. may need to be enabled in Chrome:

![chrome_site_settings](https://github.com/user-attachments/assets/f3d5003d-f5bb-430e-bd47-086ac5368c30)

![chrome_allow_clipboard_for_ayon_server](https://github.com/user-attachments/assets/aedb0396-d7e0-4b53-b08a-113f5b57f012)
