### ISSUE TITLE
🚀 Settings Experience

### ISSUE THREAD

**Issue by dee-ynput** [ynput/ayon-frontend#784]
SubEpic of [🚀 Settings Experience](https://github.com/ynput/AYON-Epics/issues/15)

- [X] Field definition support tagging
        (Complexity Level, Domain, etc...)

~~Artist settings are accessible in their profile page.~~ --> postponed
~~Settings support "Action" fields. They show up as a button in frontend and execute code when clicked. This code can read+write settings values and show dialogs.~~ --> cancelled (in favor of web-actions)

**Comment by dee-ynput** [comment]
@Innders, @flynput 
As the settings filtering is already an acclaimed improvement, we're looking at releasing this Epic ASAP and postponing other sub-issues to later.

What's your status on the hierarchy browser and the UI speed for Maya settings?
If you're close to a fix we can wait a few days and advertise them along with the filter.
In other case I would send them back to backlog and plan them as autonomous issues.

**Comment by Innders** [comment]
> hierarchy browser and the UI speed for Maya settings
No work has been started on this so I think it should go back to backlog.
