### ISSUE TITLE
Users: Deleting users should be really hard

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#796]
## Story

Deleting a user is really bad and can muck up a lot of things. Inactivating a user is prefered.

### Proposal

1. The dialog should have a warning message like the rename users dialog. It could say:
```Deleting users can have unintended consequences. Consider deactivating the user instead?```

[example]
![image](https://github.com/user-attachments/assets/45321331-3eac-4ec9-ac6c-bac5fe7a9675)

2. Deactivate user button

3. [BONUS] The user must type the username into an input to confirm they are deleting the correct user.

[github example]
![image](https://github.com/user-attachments/assets/754955f7-a37c-472c-9237-71a5dd8c24a6)

## TODO

- [ ] Warning message
- [ ] Deactivate user secondary button
- [ ] Type to delete if they do try and delete.

**Comment by martastain** [comment]
"Consider deactivating the user instead"

And add  "Deactivate user" button to the Delete user/Cancel button row
