### ISSUE TITLE
Attribute defaults: not used in entity creation

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [ynput/ayon-frontend#824]
## Story
when defining a default value of an attribute it is expected to be used when new entity is created.

### To reproduce

1. create an attribute
2. define the default value
3. create the entity and validate if the default value was used

### Additional context
![image](https://github.com/user-attachments/assets/13c46c4d-a536-4e45-9bd0-94bfffc45f3a)

![image](https://github.com/user-attachments/assets/546c3e61-1728-4a25-b216-5b6bb0752970)

**Comment by martastain** [comment]
This was discussed several times: defaults are available only for project attributes and then inherited. In your scenario, you may set "scope" to "project, folder, task". 

Project attribute (in the anatomy) should then be set to your default value and all entities will inherit it. When you set an explicit value to a folder, all underlying tasks will inherit this override from the parent folder, but you will still be able to override it again on the task level.

Having default attribute on folders/tasks in combination with inheritance would be extremely messy business.

**Comment by martastain** [comment]
One bug i realized is that when you introduce a new attribute, hierarchy is not rebuilt automatically, so the default value from the project will propagate to the entities after any change in the anatomy. I'll fix that in the backend.

**Comment by martastain** [comment]
The main issue is duplicate: https://github.com/ynput/ayon-backend/issues/264
The mentioned bug should be fixed by https://github.com/ynput/ayon-backend/pull/314 (attaching, so this issue will be closed once merged)
