### ISSUE TITLE
Bundles: Restarting server causes page crash

### ISSUE THREAD

**Issue by martastain** [ynput/ayon-frontend#861]
When the bundle page is opened and you restart the server (using `docker compose restart server`), the frontend crashes with the following error (not always)

![image](https://github.com/user-attachments/assets/bb629156-71cd-41d0-a4b3-f7c9b38fa912)

**Comment by martastain** [comment]
It happened again to me:
![image](https://github.com/user-attachments/assets/991dd96c-a7bf-42e6-98ca-858a86d6bb81)

**Comment by Innders** [comment]
Me too actually
