### ISSUE TITLE
Settings: Pasting settings snippet doesn't fill out the default values

### ISSUE THREAD

**Issue by flynput** [ynput/ayon-frontend#920]
From Discord chat
Pasted value: 
`[
{
    "plugins": [
        "CreateWriteRender"
    ],
    "nuke_node_class": "Write",
    "subsets": [
        "GreenType"
    ],
    "knobs": [
        {
            "type": "text",
            "name": "file_type",
            "value": "tiff"
        },
        {
            "type": "text",
            "name": "datatype",
            "value": "16 bit"
        },
        {
            "type": "text",
            "name": "compression",
            "value": "LZW"
        },
        {
            "type": "boolean",
            "name": "autocrop",
            "value": true
        },
        {
            "type": "color_gui",
            "name": "tile_color",
            "value": [
                74,
                223,
                0,
                255
            ]
        },
        {
            "type": "text",
            "name": "channels",
            "value": "rgb"
        },
        {
            "type": "text",
            "name": "colorspace",
            "value": "compositing_log"
        },
        {
            "type": "boolean",
            "name": "create_directories",
            "value": true
        }
    ]
}
]`

Result: 
![Image](https://github.com/user-attachments/assets/f71797cd-a65f-430f-8cc9-97e3c1f74cc1)

Expected result: pasted values should be filled out automatically if they exist, as you can see in the screenshot some of them are missing.

**Comment by martastain** [comment]
The field `value` is not defined on a `KnobModel`. What is the source of clipboard data?

**Comment by flynput** [comment]
> The field `value` is not defined on a `KnobModel`. What is the source of clipboard data?

It was discussed here: https://discord.com/channels/517362899170230292/1304204893707571281/1304210664574681118 a few weeks ago...
