### ISSUE TITLE
Settings: Permissions on project settings

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#932]
- Remove projects list from `Studio settings / permissions` and only set default.
-  ![Image](https://github.com/user-attachments/assets/fe06c6d9-476d-4ec8-a639-2b012d24b138)

- Add permissions tab to `Project settings / permissions` with the projects list to allow for project overrides.

![Image](https://github.com/user-attachments/assets/bfadd00f-0ce6-4bce-9624-8e413ca6213a)

This should work the same as how addon settings work on both studio and project levels.

**Comment by martastain** [comment]
How are we going to limit the access to this new tab in the project settings? Will that be admin/manager only or should we use project permissions in the new access group model?
