### ISSUE TITLE
Project Settings: Redirect from `manageProjects/projectSettings`

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#945]
## Problem

The user does not have access to `manageProjects/projectSettings` and tries to go to the project settings page through the app menu.

The user will land on `manageProjects/projectSettings` even though they do not have access to it. 

![Image](https://github.com/user-attachments/assets/6f9d9736-b8a7-460d-9b02-a794cc86122a)

### To reproduce

1. User has no access to project addon settings.
2. Go to settings through app menu (top right 9 dots).
3. User lands on project settings even though they do not have access.

### Expected behavior

- [x]  They should be redirected to a page they do have access to.

**Comment by flynput** [comment]
@Innders Implemented in #944
