### ISSUE TITLE
Project access: Improvements

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-frontend#946]
- [x] Remove `capitalizeFirstLetter` from project access names.

![Image](https://github.com/user-attachments/assets/62ddaa8d-2b06-4a71-993e-a4911829839a)

- [ ] Show the count of access groups on a project for selected users. For multiple users selected, show the highest count.

![Image](https://github.com/user-attachments/assets/272017e8-ba2f-48c0-98a6-f039fc824201)

- [x] User name should use `fullName || name`

![Image](https://github.com/user-attachments/assets/e8571847-46ab-4456-98ea-5b2ccd7c7cf1)

**Comment by flynput** [comment]
@Innders Apart from the group per selected users count changes were implemented in #944

**Comment by Innders** [comment]
When a lot of projects are selected, adding/removing access groups is incredibly slow (10 seconds).

If the API is too slow and cannot be improved then optimistic updating needs to be used.
